### ISSUE TITLE
Article about tracking presents only small information about the topic.

### ISSUE THREAD

**Issue by shoter** [dotnet/EntityFramework.Docs#2767]
This article present very little info about tracking. It does answer following questions:

1. How does tracking affect future queries that query the same entity?
2. What will happen if I execute for example `context.Entities.Where(e => e.Name.StartsWith("zix")` twice in the row
3. How tracking works with `TransactionScope` and overall with transactions.
4. Does `IsolationLevel` of transaction impacts tracking?
5. What are criteria for LINQ query to return tracking entity and skip SQL query?
7. Why my query inside `RepeatableRead` transaction returns cached data from queries outside transaction when I just changed data manually from db side? Why afterwards I have read lock when I am using old tracked entity? It does not make sense - did I make some kind of SQL Query then but it is not updating my entity?
9. What is lifespan of tracked entities? Do they even have lifespan?
10. Is there a limit of how many tracked entities EF can have?
11. Are there any performance considerations we should think about when using tracking?
12. How can I disable tracking for whole DbContext? Is it possible?

Therefore this article is a stub and it explains nothing of importance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Questions for @dotnet/efteam 
#2803 clarifies 1,2,5

9,10 is already answered by existing article.

I am not sure how/where/what we should document for rest.

**Comment by ajcvickers** [comment]
- [x] 1. How does tracking affect future queries that query the same entity?
- [x] 2. What will happen if I execute for example `context.Entities.Where(e => e.Name.StartsWith("zix")` twice in the row
- [ ] 3. How tracking works with `TransactionScope` and overall with transactions.
- [ ] 4. Does `IsolationLevel` of transaction impacts tracking?
- [x] 5. What are criteria for LINQ query to return tracking entity and skip SQL query?
- [ ] 7. Why my query inside `RepeatableRead` transaction returns cached data from queries outside transaction when I just changed data manually from db side? Why afterwards I have read lock when I am using old tracked entity? It does not make sense - did I make some kind of SQL Query then but it is not updating my entity?
- [ ] 8. What is lifespan of tracked entities? Do they even have lifespan?
- [x] 9. Is there a limit of how many tracked entities EF can have?
- [x] 10. Are there any performance considerations we should think about when using tracking?
- [ ] 11. How can I disable tracking for whole DbContext? Is it possible?
